event_manager/event_manager/urls.py
"""
PROJEKT URLs
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from events.api.urls import router
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("pages.urls")),
    path('admin/', admin.site.urls),
    path("events/", include("events.urls")),
    path("todos/", include("todo.urls")),
    path("accounts/login/",
         auth_views.LoginView.as_view(
             redirect_authenticated_user=True
         ), name="login"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/", include(router.urls)),  # api/category

    path(
        "schema/",
        SpectacularAPIView.as_view(api_version="v2"),
        name="schema",
    ),
    path(
        "docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    # User kann per POST einen neuen Token generieren
    path("token", obtain_auth_token, name="api-token"),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

event_manager/events/api/urls.py
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register("category", views.CategoryViewSet)
router.register("event", views.EventViewSet)

event_manager/events/urls.py
""" 
Events URLs
"""
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    # http://example.com/events/beispiel
    path("beispiel", views.test, name="test"),

    # Übersicht der Kategorien. http://example.com/events/categories
    path("categories", views.categories, name="categories"),

    # Detailseite der Kategorie 3. http://example.com/events/category/3
    path("category/<int:pk>", views.category_detail, name="category_detail"),

    # Kategorie eintragen. http://example.com/events/category/add
    path("category/add", views.category_add, name="category_add"),

    # Übersicht der Events: http://example.com/events
    path("", views.EventListView.as_view(), name="events"),

    # Detailseite des Events: http://example.com/events/3
    path("<int:pk>", views.EventDetailView.as_view(), name="event_detail"),
    path("create", views.EventCreateView.as_view(), name="event_create"),
    path("update/<int:pk>", views.EventUpdateView.as_view(), name="event_update"),
    path("delete/<int:pk>", views.EventDeleteView.as_view(), name="event_delete"),

    # events/getdata
    path("getdata", views.get_data, name="get_data"),
    path("search", views.EventSearchView.as_view(), name="search"),
]

event_manager/todo/urls.py
""" 
Events URLs
"""
from django.urls import path 
from . import views

app_name = "todo"

urlpatterns = [
    # http://127.0.0.1:8000/todos
    path("", views.todos, name="todos"),

    # http://127.0.0.1:8000/todos/3
    path("<int:pk>", views.todo_detail, name="todo_detail"),
]

event_manager/events/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.urls import reverse


User = get_user_model()  # immer das aktuell ausgewählte User-Model


def datetime_in_past(field_value) -> None:
    if field_value <= timezone.now():
        raise ValidationError(message="Der Event muss in der Zukunft liegen!")


class DateMixin(models.Model):
    """
    abstrakte Klasse: erstellt selbst keine Tabelle, sondern wird von
    anderen Klassen geerbt. Diese Klassen implementieren dann die hier
    definierten Felder.
    """
    created_at = models.DateTimeField(
        auto_now_add=True)  # beim Anlegen aktueller Timestamp
    # beim Updaten aktueller Timestamp
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Tag(models.Model):
    """Ein Tag, den man den Events zuweisen kann."""
    name = models.CharField(max_length=100)  # Varchar 100
    icon = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self) -> str:
        return self.name


class Category(DateMixin):
    """Ein Kategorie-Model.

    Dient zum Beispiel zum Erstellen einer Datenbank-Tabelle.
    """
    name = models.CharField(max_length=100)  # Varchar 100
    description = models.TextField(null=True, blank=True)
    sub_title = models.CharField(
        max_length=200, null=True, blank=True)   # optional

    class Meta:
        ordering = ["name"]  # "-name" absteigend
        verbose_name = "Kategorie"
        verbose_name_plural = "Kategorien"

    def get_absolute_url(self):
        """Das ist der Pfad zur Detailseite der Kategorie."""
        return reverse("events:category_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        """Dunder String Methode: String-Repräsentation eines Objekts."""
        return self.name


class Event(DateMixin):

    class Group(models.IntegerChoices):
        SMALL = 2, "kleine Gruppe"
        MEDIUM = 5, "mittelgroße Gruppe"
        BIG = 10, "große Gruppe"
        UNLIMITED = 0, "ohne Limit"

    class Meta:
        ordering = ["name"]
        verbose_name = "Event"
        verbose_name_plural = "Events"

    name = models.CharField(max_length=100, validators=[
        MinLengthValidator(3)
    ])  # Varchar 100
    description = models.TextField(null=True, blank=True)
    sub_title = models.CharField(max_length=200, null=True, blank=True)
    # mandatory, Dropdown im Formular
    min_group = models.IntegerField(choices=Group.choices)
    date = models.DateTimeField(validators=[datetime_in_past])
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="events",
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="events"
    )

    tags = models.ManyToManyField(
        Tag,
        related_name="events",
        blank=True
    )

    is_active = models.BooleanField(default=True)

    def related_events(self):
        """Eine Liste von ähnlichen Events."""
        qs = Event.objects.filter(
            min_group=self.min_group,
            category=self.category
        )
        return qs.exclude(pk=self.pk)

    def get_absolute_url(self):
        """Das ist der Pfad zur Model-Detailseite. Sollte immer angelegt werden,
        wenn das Model eine Detailseite hat."""
        return reverse("events:event_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.name

event_manager/events/forms.py
from django import forms
from .models import Category, Event


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = "__all__"
        exclude = ("author",)

        widgets = {
            "date": forms.DateInput(
                format=("%Y-%m-%d %H:%M"), attrs={"type": "datetime-local"}
            ),
            "tags": forms.CheckboxSelectMultiple()

        }


class EventUpdateForm(EventForm):
    """Eigenes Formular für Update Aktion."""
    class Meta(EventForm.Meta):
        fields = "__all__"


class CategoryForm(forms.ModelForm):
    """erstellt auf Basis des Models ein Formular.
    """
    class Meta:
        model = Category
        fields = "__all__"  # ["name", "description"]

event_manager/events/api/views.py
from events import models
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .serializers import CategorySerializer, EventSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    """Implementiert alle nötigen Endpunkte."""
    serializer_class = CategorySerializer
    queryset = models.Category.objects.all()


class EventViewSet(viewsets.ModelViewSet):
    """Implementiert alle nötigen Endpunkte."""
    serializer_class = EventSerializer
    queryset = models.Event.objects.all()
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

event_manager/events/views.py
from django.db import transaction, DatabaseError
from typing import Any
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpRequest, HttpResponse, Http404, JsonResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Category, Event
from .forms import CategoryForm, EventForm
from event_manager.utils import get_database


class UserIsAuthor(UserPassesTestMixin):
    """return True, if user is author or member of moderatoren group"""

    def test_func(self) -> bool:
        return (
            self.get_object().author == self.request.user
            # or self.request.user.groups.filter(name="moderators").exists()
        )


class ViewPermission(PermissionRequiredMixin):
    permission_required = ("events.view_event",)


class EventDeleteView(SuccessMessageMixin, UserIsAuthor, DeleteView):
    """Generische Delete-View. 

    Template: event_confirm_delete.html
    """
    model = Event
    success_message = "Event wurde erfolgreich gelöscht"
    success_url = reverse_lazy("events:events")


class EventUpdateView(SuccessMessageMixin, UserIsAuthor, UpdateView):
    model = Event
    form_class = EventForm
    # success_url = reverse_lazy("events:events")
    success_message = "Event wurde erfolgreich upgedated"


class EventCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """Generische Create View. Nach dem Eintragen wird Weitergeleitet an 
    get_absolute_url im Model.

    Template: event_form.html
    """
    model = Event
    form_class = EventForm
    # success_url = reverse_lazy("events:events")
    success_message = "Event wurde erfolgreich eingetragen"

    def form_valid(self, form):
        """Wird aufgerufen, bevor es in die DB
        eingetragen wird."""
        # messages.info(self.request, "Three credits remain in your account.")
        form.instance.author = self.request.user
        return super().form_valid(form)


class EventSearchView(ListView):
    """Filtert Events nach einer Suche mit der Suchbox.

    /events/search?q=<SUCHBEGRIFF>
    """
    model = Event
    queryset = Event.objects.select_related("author", "category").all()

    def get_context_data(self, **kwargs):
        """Render-Context erweitern."""
        context = super().get_context_data(**kwargs)
        context["searched"] = self.request.GET.get("q")
        return context

    def get_queryset(self):

        q = self.request.GET.get("q")
        if not q:
            return Event.objects.none()

        qs = super().get_queryset()
        qs = qs.filter(name__contains=q)
        return qs


class EventListView(ListView):
    """Generische listview 

    events/?q=abc

    template liegt unter:
    events/event_list.html.
    object_list steht im Template zur verfügung

    """
    model = Event
    queryset = Event.objects.select_related("author", "category").all()
    paginate_by = 10
    # template_name = "events/events.html"
    # context_object_name = "events"


class EventDetailView(DetailView):
    """Generische Detailview.

    class EventDetailView(ViewPermission, DetailView). 

    template events/event_detail.html
    object steht im Template zur verfügung
    """
    model = Event


def get_data(request: HttpRequest) -> HttpResponse:
    """Diese View gibt JSON zurück.

    Die kann dann auch per JS fetch aufgerufen werden.
    """
    data = [12, 133, 34, 23, 14]

    return JsonResponse(data, safe=False)


def category_add(request: HttpRequest) -> HttpResponse:
    """
    Eine neue Kategorie eintragen.
    http://127.0.0.1/events/category/add
    """
    if request.method == "POST":
        # hier sollen die Daten in die DB eingetragen werden
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            messages.success(request, "Category wurde erfolgreich angelegt!")
            # Weiterleiten auf gerade anlegte Kategorie
            # return redirect("events:category_detail", category.pk)
            return redirect(category)   # get_absolute_url() wird aufgerufen
            #  return redirect("events:categories") ## Weiterleiten auf Kategorieübersicht

        messages.error(request, "Category konnte nicht angelegt werden!")
    else:
        # hier soll ein leeres Formular engzeigt werden
        form = CategoryForm()

    return render(
        request,
        "events/category_add.html",
        {
            "form": form
        }
    )


def categories(request: HttpRequest) -> HttpResponse:
    """
    Übersicht aller Kategorien
    http://127.0.0.1/events/categories
    """
    # print("GET Daten:", request.GET.get("x"))
    categories = Category.objects.all()
    context = {
        "categories": categories
    }

    return render(
        request,
        "events/categories.html",
        context
    )


def category_detail(request: HttpRequest, pk: int):
    """
    Detailseite einer Kategorie
    http://127.0.0.1/events/category/3
    """
    try:
        category = Category.objects.get(pk=pk)
    except Category.DoesNotExist:
        raise Http404("Does not exist.")

    return render(
        request,
        "events/category_detail.html",
        {
            "category": category
        }
    )


@transaction.atomic
def test_db(request):
    try:
        result = Event.objects.all()
    except DatabaseError as e:
        print(e)
        return redirect("/")


def test(request: HttpRequest):
    """ 
    http://127.0.0.1/events/beispiel
    ein View ist ein Controller, der zwei Mindestanforderungen hat:
    - er erhält immer ein reqeust-Objekt als Argument
    - eine View MUSS immer ein Http-Response-Objekt zurückgeben
    - einzige Ausnahme: es wird eine Exception ausgelöst (zb. 404 Fehler)
    """
    d = [
        3,
        4
    ]

    return render(
        request,
        "events/render_test.html",
        {
            "test": d
        }
    )

event_manager/events/templates/events/categories.html
{% extends "base.html" %}

{% block header %}
<h1>Übersicht der Kategorien</h1>
{% endblock %}


{% block content %}
<a href="{% url 'events:category_add' %}">Kategorie hinzufügen</a><br>
<ul>
    {% for category in categories %}
    <li><a href="{% url 'events:category_detail' category.pk %}">{{category}}</a></li>
    {% endfor %}
</ul>
{% endblock %}

event_manager/events/templates/events/category_add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block header %}
<h1>neue Kategorie eintragen</h1>
{% endblock %}

{% block content %}
<div class="col-12">

    <form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <div>
        <button class="btn btn-primary">Absenden</button>
    </div>
    </form>

</div>
{% endblock %}

event_manager/events/templates/events/category_detail.html
{% extends "base.html" %}

{% block header %}
<h1>{{category|upper}}</h1>
<a href="{% url 'events:categories' %}">zurück zur Übersicht</a>
{% endblock %}

{% block content %}
<p>{{category.sub_title|default:'nicht vorhanden'}}</p>
<p>{{category.description|upper|linebreaks}}</p>
{% endblock %}

event_manager/events/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block header %}
<h1>Event löschen: {{object}}</h1>
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Willst du das Event sicher löschen? "{{ object }}"?</p>
        <input type="submit" class="btn btn-primary" value="Ja, weg damit!">
    </form>

{% endblock %}

event_manager/events/templates/events/event_detail.html
{% extends 'base.html' %}

{% block header %}
<h1 class="display-6 fw-bold lh-1">{{object.name}}</h1>
<h3 class="display-6 lh-3">{{object.sub_title}}</h3>

<p>
am <b>{{object.date}} Uhr</b>, eingestellt von  {{object.author}}
in <a href="{% url 'events:category_detail' object.category.pk %}">
{{object.category}}</a>
</p>

{% if user == object.author %}
<p>
  <a href="{% url 'events:event_update' object.pk %}">Event editieren</a> | 
  <a href="{% url 'events:event_delete' object.pk %}">Event löschen</a>
</p>
{% endif %}

{% endblock %}

{% block content %}
<div class="container">
<div class="col-lg-8 col-sm-12">

<h3>Beschreibung</h3>
<p>{{object.description}}</p>

<section class="mb-5 mt-5">
<h3>zusätzliche Infos</h3>

<ul>
  <li>eingestellt am: {{object.created_at}}</li>
  <li>eingestellt von: {{object.author}}</li>
  <li><b>findet statt am (deutsche Zeit): {{object.date}}</b></li>
  <li>Min Gruppengröße: {{object.get_min_group_display}}</li>
  <li>Min Gruppengröße: {{object.min_group}}</li>
  <li>Tags: {{object.tags.all|join:", "}}</li>
</ul>
</section>

{% comment %}
Ähnliche Events nur anzeigen, wenn Einträge vorhanden
{% if object.related_events.exists %}
  <section class="mb-5 mt-5">
  <h3>Ähnliche Events</h3>
  <ul>
  {% for event in object.related_events %}
    <li>{{event}}</li>
  {% endfor %}
  </ul>
  </section>
{% endif %}
{% endcomment %}

<section class="mb-5 mt-5">
  <h3>Ähnliche Events</h3>
  <ul>
  {% for event in object.related_events %}
    <li>{{event}}</li>
  {% empty %}
    <li>Leider befinden sich keine ähnlichen Events im System</li>
  {% endfor %}
  </ul>
  </section>


</div>
</div>

<canvas id="polar-chart" width="800" height="450"></canvas>

<script
src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js">
</script>

<script>
/*
Beispiel, wie man ein JS Chart mit einem Ajax-Aufruf mit Daten 
von Django füllen kann. Fetch holt dazu die Daten von dem Endpunkt
und wandelt sie per json in einen Json-Stream um, der dann an Chart
übergeben wird.
*/


window.addEventListener("load", (event) => {
  console.log("page is fully loaded");
  fetch('/events/getdata')
    .then(response => response.json())
    .then(data => {

        new Chart(document.getElementById("polar-chart"), {
            type: 'polarArea',
            data: {
              labels: ["Africa", "Asia", "Europe", "Latin America",
"North America"],
              datasets: [
                {
                  label: "Population (millions)",
                  backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                  data: data
                }
              ]
            },
            options: {
              title: {
                display: true,
                text: 'Predicted world population (millions) in 2050'
              }
            }
        });
    })
    .catch(error => console.error('Error:', error));
});
</script>

{%endblock%}

event_manager/events/templates/events/event_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block header %}
<h1>neues Event eintragen</h1>
{% endblock %}

{% block content %}
<div class="col-12">

    <form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <div>
        <button class="btn btn-primary">Absenden</button>
    </div>
    </form>

</div>
{% endblock %}

event_manager/events/templates/events/event_list.html
{% extends 'base.html' %}

{% block title %}
Event Übersicht
{% endblock %}

{% block header %}
<h1 class="display-6 fw-bold lh-1">Event Übersicht</h1>
<p>Tolle Events in deiner Nähe</p>

{% if searched %}
<p>Ihr Suchwort: {{searched}}</p>
{% endif %}

<p><a href="{% url 'events:event_create' %}">Neuen Event hinzufügen</a></p>

{% endblock %}

{% block content %}
<ul class="list-group event_box">
{% for event in event_list %}
<a href="{% url 'events:event_detail' event.pk %}">

    <li class="list-group-item rounded">
    <small><span>am {{event.date}}</span></small><br>
    <b>{{event.name}}</b>
        <span class="badge rounded-pill bg-primary">{{event.category}}</span>
        <p>by {{event.author}}</p>
    </li>
    
</a>
{% endfor%}
</ul>


{% include "../snippets/paginator.html" %}

{%endblock%}

event_manager/events/templates/events/render_test.html
{% for el in test %}
    {{el}}
{% endfor %}